### PR TITLE
Retry CURLE_PARTIAL_FILE 

### LINKED ISSUE #26: Retry CURLE_PARTIAL_FILE (cURL error 18)
`CURLE_PARTIAL_FILE` -- https://curl.haxx.se/libcurl/c/libcurl-errors.html
This should maybe be retried?

full stack trace:
```
CRITICAL: GuzzleHttp\Exception\RequestException:cURL error 18: transfer closed with 93525720 bytes remaining to read (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"errFile":"/code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php","errLine":186,"errCode":200,"errTrace":"#0 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#3 /code/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#4 /code/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#5 /code/vendor/guzzlehttp/guzzle/src/RetryMiddleware.php(67): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#6 /code/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\\RetryMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#7 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#8 /code/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#9 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#10 /code/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#11 /code/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#12 /code/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)\n#13 /code/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Client->requestAsync('get', Object(GuzzleHttp\\Psr7\\Uri), Array)\n#14 /code/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('get', Object(GuzzleHttp\\Psr7\\Uri), Array)\n#15 /code/src/HttpExtractor.php(39): GuzzleHttp\\Client->__call('get', Array)\n#16 /code/src/HttpExtractorComponent.php(41): Keboola\\HttpExtractor\\HttpExtractor->extract(Object(GuzzleHttp\\Psr7\\Uri), '/data/out/files...')\n#17 /code/src/run.php(14): Keboola\\HttpExtractor\\HttpExtractorComponent->run()\n#18 {main}","errPrevious":""
```

### PR DESCRIPTION
**Pull request by tomasfejfar**
Fixes #26

### CODE REVIEW

File: src/Client/RetryDecider.php [hunk 1]
```diff
@@ -68,13 +68,14 @@ private function isCurlRetryCode(int $curlErrorNumber): bool
...
         return in_array($curlErrorNumber, [
-            CURLE_COULDNT_RESOLVE_PROXY,
-            CURLE_COULDNT_RESOLVE_HOST,
             CURLE_COULDNT_CONNECT,
-            CURLE_OPERATION_TIMEOUTED,
-            CURLE_SSL_CONNECT_ERROR,
+            CURLE_COULDNT_RESOLVE_HOST,
+            CURLE_COULDNT_RESOLVE_PROXY,
             CURLE_GOT_NOTHING,
+            CURLE_OPERATION_TIMEOUTED,
```
Comment (pivnicek) [inline src/Client/RetryDecider.php:75]: I had to check this one because it seemed strangely named, but 👍

**Review by pivnicek — APPROVED** [review]
👍
